---

- name: Install homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install homebrew items
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_items }}"
