---

# Complete configuration of a (well, my) workstation. Includes pretty much everything
# I need for daily tasks, programming, and work.
#
- name: workstation setup
  hosts: localhost

  # Adding the roles one-by-one as I get them ported from my personal implementation.
  roles:
    - security
    - dotfiles
    - homebrew
    - homebrew_items
    - brewcask_items
    - ruby
    - virtualbox_vagrant
    # # Note: if you are running the playbook against the local machine, installing Python will make Ansible
    # # very unhappy. Only do this if you're running against a remote machine.
    # - python

  environment:
    PATH: "~/.rbenv/shims:~/bin:/usr/local/bin:/usr/local/opt:/usr/local:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
