---

- name: Install Python taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ python_taps }}"

- name: Install Python
  homebrew:
    name: "python"
    state: present

- name: Install Python items
  shell: "pip install --upgrade {{ item }}"
  with_items: python_items
