---

python_taps:
  - homebrew/python

python_items:
  - coverage
  - ecdsa
  - Jinja2
  - markupsafe
  - mock
  - nose
  - paramiko
  - punic
  - pycparser
  - pycrypto
  - pyyaml
  - six
  - xunique
