---

brewcask_taps:
  - caskroom/cask

brewcask_items:
  - a-better-finder-rename
  - android-studio
  - atom
  - charles
  - clamxav
  - cleanmymac
  - dash
  - duet
  - fauxpas
  - firefox
  - gitup
  - github-desktop
  - hazel
  - little-snitch
  - macpaw-gemini
  - malwarebytes-anti-malware
  - onyx
  - provisionql
  - quicklook-csv
  - quicklook-json
  - slack
  - sourcetree
  # # Note: because, who doesn't want to play Star Realms??
  - starrealms
  # # Other items, which I don't always want to install
  # - eclipse-ide
  # - pycharm
  # - rstudio
  # - scala-ide
