---

brewcask_taps:
  - caskroom/cask

brewcask_items:
  - a-better-finder-attribute
  - a-better-finder-rename
  - atom
  - backblaze
  - backblaze-downloader
  - calibre
  - clamxav
  - cleanmymac
  - dash
  - duet
  - firefox
  - gitup
  - java7
  - java
  - kaleidoscope
  - little-snitch
  - macpaw-gemini
  - malwarebytes-anti-malware
  - onyx
  - slack
  - sourcetree
  # # Note: because, who doesn't want to play Star Realms??
  - starrealms
  - sublime-text
  - xquartz
  # # Other items, which I don't always want to install
  # - pycharm
  # - rstudio