---

- name: Install brew cask taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ brewcask_taps }}"

- name: Install brew cask items
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ brewcask_items }}"
