---

- name: Ensure ruby is installed via homebrew
  homebrew:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ ruby_homebrew_items }}"

- name: Install base gems
  gem:
    name: "{{ item }}"
    state: present
  with_items: "{{ ruby_gems }}"

- name: Deploy Gemfile
  copy:
    src="Gemfile"
    dest="{{ ansible_env.HOME }}/Gemfile"
    owner="{{ ansible_env.USER }}"
    group=staff
    mode=0644

- name: Install gems with bundler
  bundler:
    state: present
    gemfile: "{{ ansible_env.HOME }}/Gemfile"
    user_install: false
